#!/bin/bash

LOGS_FOLDER="/var/log/roboshop"
sudo mkdir -p $LOGS_FOLDER
sudo chown -R ec2-user:ec2-user $LOGS_FOLDER
sudo chmod -R 755 $LOGS_FOLDER
LOGS_FILE="$LOGS_FOLDER/$0.log"
TIMESTAMP=$(date "+%Y-%m-%d-%H:%M:%S")

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"


USER_ID=$(id -u)
if [ $USER_ID -ne 0 ]; then
 echo -e "$TIMESTAMP [ERROR] $R YOU SHOULD BE RUN AS ROOT USER $N" | tee -a $LOGS_FILE
  exit 1

fi
   echo "$TIMESTAMP [info] $G you should br run with  root access $Y" |  tee -a $LOGS_FILE
 
## fir arg -- what you are install
## second ard-- exit code


VALIDATE (){
    if [ $1 -ne 0 ]; then
     echo -e "$TIMESTAMP [ERROR] $2 ... $R FIALURE... $N" | tee -a $LOGS_FILE
       exit 1
    else
       echo -e "INFORM IT  when $2...$G SUCCESS $Y" | tee -a $LOGS_FILE
     fi  
}


cp mongo.repo /etc/yum.repos.d/mongo.repo
  VALIDATE $? "Adding mongo repo"

   dnf install mongodb-org -y | tee -a $LOGS_FILE
    VALIDATE $? "install mongodb"

    systemctl enable mongod | tee -a $LOGS_FILE
    VALIDATE $? "enable mongb"
     systemctl start mongod  | tee -a $LOGS_FILE
      VALIDATE $? "start mongodb"

       sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf
      VALIDATE $? "Allowing the remote connection to mongodb"
        
        systemctl restart mongod
         VALIDATE $? "restart the mongodb"